name: sukhad_yathra
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  firebase_auth: ^0.14.0+5
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+5
  google_sign_in: ^4.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - images/
